#!/usr/bin/env python
import sys
import picklemyplot as pp
import matplotlib.pyplot as plt

try:
	fig=pp.loadfiginteractive(sys.argv[1])
except:
	print "Filename error"
	print "usage : loadfig filename"
plt.show()
